/**
 * Job Notification Tracker - Realistic Indian Tech Jobs Dataset
 * 60 jobs with varied companies, roles, locations, and details
 */

const jobData = [
  {
    id: 1,
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://amazon.jobs/en/jobs/123456",
    description: "Join Amazon's internship program to work on real-world projects. You'll collaborate with experienced engineers on scalable systems. Gain hands-on experience with AWS services and distributed systems. Perfect opportunity for students passionate about software engineering."
  },
  {
    id: 2,
    title: "Graduate Engineer Trainee",
    company: "Infosys",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Spring Boot", "REST APIs"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.infosys.com/job/123456",
    description: "Infosys is hiring fresh graduates for our Graduate Engineer Trainee program. You'll undergo comprehensive training in enterprise software development. Work on client projects using cutting-edge technologies. Build a strong foundation for your IT career."
  },
  {
    id: 3,
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "Express", "JavaScript"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://razorpay.com/careers/junior-backend-dev",
    description: "Razorpay is looking for a Junior Backend Developer to join our payments team. You'll build APIs that process millions of transactions daily. Work with microservices architecture and cloud infrastructure. Great learning opportunity in fintech."
  },
  {
    id: 4,
    title: "Frontend Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "HTML"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://careers.swiggy.com/internships/frontend",
    description: "Swiggy's frontend team is offering internships to build user-facing features. You'll work on React components and improve user experience. Learn from senior developers in a fast-paced startup environment. Perfect for students interested in frontend development."
  },
  {
    id: 5,
    title: "Java Developer (0-1)",
    company: "TCS",
    location: "Chennai",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "Hibernate", "MySQL"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "4–6 LPA",
    applyUrl: "https://careers.tcs.com/job/java-developer",
    description: "TCS is hiring Java developers with 0-1 years of experience. You'll work on enterprise applications for global clients. Learn best practices in software development. Join a team of experienced professionals in a stable work environment."
  },
  {
    id: 6,
    title: "Python Developer (Fresher)",
    company: "Zoho",
    location: "Chennai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "5–7 LPA",
    applyUrl: "https://careers.zoho.com/python-developer",
    description: "Zoho is looking for fresh Python developers to join our product development team. You'll build scalable web applications using Django. Work on products used by millions of users worldwide. Great culture and learning opportunities."
  },
  {
    id: 7,
    title: "React Developer (1-3)",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "Jest"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://phonepe.com/careers/react-developer",
    description: "PhonePe is hiring React developers with 1-3 years of experience. Build user interfaces for our payment app used by millions. Work with modern React patterns and TypeScript. Join India's leading fintech company."
  },
  {
    id: 8,
    title: "QA Intern",
    company: "Wipro",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "Java", "TestNG"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹18k–₹30k/month Internship",
    applyUrl: "https://careers.wipro.com/qa-intern",
    description: "Wipro's QA team is offering internships to learn software testing. You'll work on test case design and automation. Gain experience with testing tools and frameworks. Perfect for students interested in quality assurance."
  },
  {
    id: 9,
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Pandas", "Data Visualization"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://flipkartcareers.com/data-analyst-intern",
    description: "Flipkart is looking for Data Analyst interns to work on business intelligence. Analyze customer behavior and sales data. Create reports and dashboards for stakeholders. Great opportunity to learn data analytics in e-commerce."
  },
  {
    id: 10,
    title: "Full Stack Developer",
    company: "CRED",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "Node.js", "MongoDB", "TypeScript"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "12–20 LPA",
    applyUrl: "https://cred.club/careers/fullstack-dev",
    description: "CRED is hiring Full Stack Developers to build features for our credit card rewards platform. Work on both frontend and backend systems. Use modern technologies in a fast-growing startup. Great compensation and equity."
  },
  {
    id: 11,
    title: "Backend Developer",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "Microservices", "Kafka"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "8–15 LPA",
    applyUrl: "https://paytm.com/careers/backend-dev",
    description: "Paytm is looking for Backend Developers to work on payment processing systems. Build scalable APIs handling millions of transactions. Work with microservices and event-driven architecture. Join India's leading payment platform."
  },
  {
    id: 12,
    title: "DevOps Engineer",
    company: "Accenture",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "1-3",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "7–12 LPA",
    applyUrl: "https://accenture.com/careers/devops-engineer",
    description: "Accenture is hiring DevOps Engineers to manage cloud infrastructure. Work with AWS, Docker, and Kubernetes. Set up CI/CD pipelines for client projects. Great opportunity to learn cloud technologies."
  },
  {
    id: 13,
    title: "Mobile App Developer",
    company: "Juspay",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["React Native", "JavaScript", "Android", "iOS"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://juspay.in/careers/mobile-dev",
    description: "Juspay is looking for Mobile App Developers to build payment SDKs. Work with React Native to create cross-platform apps. Build features used by millions of users. Join a fintech company focused on payments."
  },
  {
    id: 14,
    title: "UI/UX Designer",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Figma", "UI Design", "Prototyping", "User Research"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "5–8 LPA",
    applyUrl: "https://freshworks.com/careers/ui-ux-designer",
    description: "Freshworks is hiring UI/UX Designers to design SaaS products. Create user interfaces for business software. Work with product managers and developers. Build designs that millions of users interact with daily."
  },
  {
    id: 15,
    title: "Cloud Engineer",
    company: "Capgemini",
    location: "Pune",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Azure", "AWS", "Terraform", "Python"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "8–14 LPA",
    applyUrl: "https://capgemini.com/careers/cloud-engineer",
    description: "Capgemini is looking for Cloud Engineers to manage cloud infrastructure. Work with Azure and AWS platforms. Automate deployments using Terraform. Join a global IT consulting company."
  },
  {
    id: 16,
    title: "Machine Learning Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "TensorFlow", "Machine Learning", "Data Science"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://ibm.com/careers/ml-intern",
    description: "IBM is offering Machine Learning internships to work on AI projects. Build and train ML models. Work with large datasets and cloud infrastructure. Great opportunity to learn AI/ML from industry experts."
  },
  {
    id: 17,
    title: "Software Engineer",
    company: "Oracle",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Java", "Oracle DB", "PL/SQL", "Spring"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "10–16 LPA",
    applyUrl: "https://oracle.com/careers/software-engineer",
    description: "Oracle is hiring Software Engineers to work on database products. Build enterprise software used by Fortune 500 companies. Work with Oracle database and Java technologies. Join a leading enterprise software company."
  },
  {
    id: 18,
    title: "Frontend Developer",
    company: "SAP",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Angular", "TypeScript", "SCSS", "RxJS"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://sap.com/careers/frontend-dev",
    description: "SAP is looking for Frontend Developers to build enterprise software interfaces. Work with Angular and TypeScript. Create user interfaces for business applications. Join a global enterprise software company."
  },
  {
    id: 19,
    title: "Backend Intern",
    company: "Cognizant",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Spring Boot", "REST APIs", "MySQL"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://cognizant.com/careers/backend-intern",
    description: "Cognizant is offering Backend Development internships. Learn enterprise software development. Work on REST APIs and microservices. Gain experience in a global IT services company."
  },
  {
    id: 20,
    title: "Full Stack Intern",
    company: "Dell",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Node.js", "MongoDB", "JavaScript"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://dell.com/careers/fullstack-intern",
    description: "Dell is looking for Full Stack interns to work on internal tools. Build web applications using React and Node.js. Learn full-stack development in a corporate environment. Great learning opportunity."
  },
  {
    id: 21,
    title: "SDE Intern",
    company: "Microsoft",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C#", ".NET", "Azure", "SQL Server"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹35k–₹55k/month Internship",
    applyUrl: "https://microsoft.com/careers/sde-intern",
    description: "Microsoft is offering SDE internships to work on cloud products. Build features for Azure platform. Work with C# and .NET technologies. Learn from world-class engineers at Microsoft."
  },
  {
    id: 22,
    title: "Python Developer",
    company: "ThoughtWorks",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["Python", "Django", "PostgreSQL", "Docker"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "12–18 LPA",
    applyUrl: "https://thoughtworks.com/careers/python-dev",
    description: "ThoughtWorks is hiring Python Developers to work on client projects. Build scalable web applications using Django. Work in agile teams with global clients. Great culture and learning opportunities."
  },
  {
    id: 23,
    title: "React Native Developer",
    company: "Uber",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React Native", "TypeScript", "Redux", "Jest"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "15–25 LPA",
    applyUrl: "https://uber.com/careers/react-native-dev",
    description: "Uber is looking for React Native Developers to build mobile apps. Work on features used by millions of riders and drivers. Use modern React Native patterns. Join a global tech company."
  },
  {
    id: 24,
    title: "Backend Developer",
    company: "Ola",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "Kafka", "Redis"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "7–12 LPA",
    applyUrl: "https://ola.com/careers/backend-dev",
    description: "Ola is hiring Backend Developers to work on ride-sharing platform. Build APIs handling millions of requests. Work with microservices and event-driven architecture. Join India's leading mobility platform."
  },
  {
    id: 25,
    title: "Frontend Developer",
    company: "Myntra",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "Next.js", "TypeScript", "CSS"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–16 LPA",
    applyUrl: "https://myntra.com/careers/frontend-dev",
    description: "Myntra is looking for Frontend Developers to build e-commerce interfaces. Work on React and Next.js applications. Create user experiences for fashion shopping. Join India's leading fashion e-commerce platform."
  },
  {
    id: 26,
    title: "Data Engineer",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Spark", "Kafka", "Airflow"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "12–20 LPA",
    applyUrl: "https://zomato.com/careers/data-engineer",
    description: "Zomato is hiring Data Engineers to build data pipelines. Process millions of food orders daily. Work with big data technologies like Spark and Kafka. Join India's leading food delivery platform."
  },
  {
    id: 27,
    title: "QA Engineer",
    company: "MakeMyTrip",
    location: "Gurgaon",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Selenium", "Java", "TestNG", "API Testing"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "5–8 LPA",
    applyUrl: "https://makemytrip.com/careers/qa-engineer",
    description: "MakeMyTrip is looking for QA Engineers to test travel booking platform. Write automated test cases using Selenium. Ensure quality of features used by millions. Join India's leading travel platform."
  },
  {
    id: 28,
    title: "DevOps Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹22k–₹38k/month Internship",
    applyUrl: "https://razorpay.com/careers/devops-intern",
    description: "Razorpay is offering DevOps internships to learn cloud infrastructure. Work with AWS, Docker, and Kubernetes. Set up CI/CD pipelines. Great opportunity to learn DevOps in fintech."
  },
  {
    id: 29,
    title: "Full Stack Developer",
    company: "Unacademy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Node.js", "MongoDB", "GraphQL"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://unacademy.com/careers/fullstack-dev",
    description: "Unacademy is hiring Full Stack Developers to build education platform. Work on features for online learning. Use React, Node.js, and GraphQL. Join India's leading edtech company."
  },
  {
    id: 30,
    title: "Backend Developer",
    company: "Byju's",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "MySQL", "Redis"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://byjus.com/careers/backend-dev",
    description: "Byju's is looking for Backend Developers to work on learning platform. Build APIs for educational content delivery. Work with microservices architecture. Join India's leading edtech company."
  },
  {
    id: 31,
    title: "Frontend Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "TypeScript", "CSS", "JavaScript"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹28k–₹45k/month Internship",
    applyUrl: "https://cred.club/careers/frontend-intern",
    description: "CRED is offering Frontend Development internships. Build user interfaces for credit card rewards platform. Work with React and TypeScript. Learn frontend development in fintech."
  },
  {
    id: 32,
    title: "SDE Intern",
    company: "Google",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C++", "Python", "Algorithms", "Data Structures"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹40k–₹60k/month Internship",
    applyUrl: "https://google.com/careers/sde-intern",
    description: "Google is offering SDE internships to work on Google products. Build features used by billions of users. Work with world-class engineers. Learn software engineering at Google."
  },
  {
    id: 33,
    title: "Python Developer",
    company: "ShareChat",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["Python", "Django", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "12–20 LPA",
    applyUrl: "https://sharechat.com/careers/python-dev",
    description: "ShareChat is hiring Python Developers to build social media platform. Work on features for millions of users. Use Django and PostgreSQL. Join India's leading social media platform."
  },
  {
    id: 34,
    title: "React Developer",
    company: "Meesho",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "JavaScript", "Redux", "CSS"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://meesho.com/careers/react-dev",
    description: "Meesho is looking for React Developers to build social commerce platform. Create user interfaces for e-commerce. Work with React and Redux. Join India's leading social commerce platform."
  },
  {
    id: 35,
    title: "Backend Developer",
    company: "Dream11",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "Kafka", "MongoDB"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "15–25 LPA",
    applyUrl: "https://dream11.com/careers/backend-dev",
    description: "Dream11 is hiring Backend Developers to work on fantasy sports platform. Build APIs handling millions of users. Work with microservices and real-time systems. Join India's leading fantasy sports platform."
  },
  {
    id: 36,
    title: "Full Stack Developer",
    company: "Rapido",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["React", "Node.js", "MongoDB", "TypeScript"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "7–12 LPA",
    applyUrl: "https://rapido.bike/careers/fullstack-dev",
    description: "Rapido is looking for Full Stack Developers to build bike taxi platform. Work on both frontend and backend systems. Use React and Node.js. Join India's leading bike taxi platform."
  },
  {
    id: 37,
    title: "Mobile Developer",
    company: "InMobi",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Android", "Kotlin", "Java", "REST APIs"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "10–16 LPA",
    applyUrl: "https://inmobi.com/careers/mobile-dev",
    description: "InMobi is hiring Mobile Developers to build advertising SDKs. Work on Android apps used by millions. Use Kotlin and Java. Join India's leading mobile advertising platform."
  },
  {
    id: 38,
    title: "Data Scientist",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Machine Learning", "SQL", "Pandas"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "12–20 LPA",
    applyUrl: "https://flipkartcareers.com/data-scientist",
    description: "Flipkart is looking for Data Scientists to work on recommendation systems. Build ML models for e-commerce. Analyze customer behavior data. Join India's leading e-commerce platform."
  },
  {
    id: 39,
    title: "DevOps Engineer",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "12–18 LPA",
    applyUrl: "https://phonepe.com/careers/devops-engineer",
    description: "PhonePe is hiring DevOps Engineers to manage payment infrastructure. Work with AWS and Kubernetes. Set up CI/CD pipelines. Join India's leading payment platform."
  },
  {
    id: 40,
    title: "Frontend Developer",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "JavaScript", "CSS", "Redux"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "6–10 LPA",
    applyUrl: "https://zomato.com/careers/frontend-dev",
    description: "Zomato is looking for Frontend Developers to build food delivery interfaces. Create user experiences for ordering food. Work with React and Redux. Join India's leading food delivery platform."
  },
  {
    id: 41,
    title: "Backend Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹24k–₹38k/month Internship",
    applyUrl: "https://careers.swiggy.com/internships/backend",
    description: "Swiggy is offering Backend Development internships. Build APIs for food delivery platform. Learn Django and PostgreSQL. Great opportunity to learn backend development in food tech."
  },
  {
    id: 42,
    title: "Full Stack Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "Node.js", "MongoDB", "TypeScript"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "15–25 LPA",
    applyUrl: "https://razorpay.com/careers/fullstack-dev",
    description: "Razorpay is hiring Full Stack Developers to build payment products. Work on both frontend and backend systems. Use React, Node.js, and TypeScript. Join India's leading payment gateway."
  },
  {
    id: 43,
    title: "SDE Intern",
    company: "Amazon",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://amazon.jobs/en/jobs/234567",
    description: "Join Amazon's internship program in Hyderabad. Work on real-world projects with experienced engineers. Gain hands-on experience with AWS services. Perfect opportunity for students."
  },
  {
    id: 44,
    title: "Java Developer",
    company: "Infosys",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "Microservices", "MySQL"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "8–14 LPA",
    applyUrl: "https://careers.infosys.com/job/java-developer-2",
    description: "Infosys is hiring Java Developers with 1-3 years of experience. Work on enterprise applications for global clients. Use Spring Boot and microservices. Join a leading IT services company."
  },
  {
    id: 45,
    title: "React Developer",
    company: "TCS",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "JavaScript", "CSS", "REST APIs"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "5–8 LPA",
    applyUrl: "https://careers.tcs.com/job/react-developer",
    description: "TCS is looking for React Developers to build web applications. Work on client projects using React. Learn enterprise software development. Join a stable IT services company."
  },
  {
    id: 46,
    title: "Python Developer",
    company: "Wipro",
    location: "Pune",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Python", "Django", "PostgreSQL", "Docker"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "7–12 LPA",
    applyUrl: "https://careers.wipro.com/python-developer",
    description: "Wipro is hiring Python Developers to work on client projects. Build web applications using Django. Work with PostgreSQL and Docker. Join a global IT services company."
  },
  {
    id: 47,
    title: "Frontend Developer",
    company: "Accenture",
    location: "Chennai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Angular", "TypeScript", "SCSS", "RxJS"],
    source: "Indeed",
    postedDaysAgo: 10,
    salaryRange: "5–9 LPA",
    applyUrl: "https://accenture.com/careers/frontend-dev",
    description: "Accenture is looking for Frontend Developers to build enterprise applications. Work with Angular and TypeScript. Create user interfaces for business software. Join a global consulting company."
  },
  {
    id: 48,
    title: "Backend Developer",
    company: "Capgemini",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "Kafka", "MySQL"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "8–14 LPA",
    applyUrl: "https://capgemini.com/careers/backend-dev",
    description: "Capgemini is hiring Backend Developers to work on client projects. Build APIs using Spring Boot. Work with Kafka for event-driven architecture. Join a global IT consulting company."
  },
  {
    id: 49,
    title: "Full Stack Developer",
    company: "Cognizant",
    location: "Chennai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "Node.js", "MongoDB", "JavaScript"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://cognizant.com/careers/fullstack-dev",
    description: "Cognizant is looking for Full Stack Developers to build web applications. Work on both frontend and backend systems. Use React and Node.js. Join a global IT services company."
  },
  {
    id: 50,
    title: "Mobile Developer",
    company: "IBM",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React Native", "JavaScript", "Redux", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–16 LPA",
    applyUrl: "https://ibm.com/careers/mobile-dev",
    description: "IBM is hiring Mobile Developers to build enterprise mobile apps. Work with React Native to create cross-platform apps. Build features for business users. Join a leading enterprise software company."
  },
  {
    id: 51,
    title: "QA Engineer",
    company: "Oracle",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Selenium", "Java", "TestNG", "API Testing"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "5–8 LPA",
    applyUrl: "https://oracle.com/careers/qa-engineer",
    description: "Oracle is looking for QA Engineers to test database products. Write automated test cases using Selenium. Ensure quality of enterprise software. Join a leading enterprise software company."
  },
  {
    id: 52,
    title: "DevOps Engineer",
    company: "SAP",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–16 LPA",
    applyUrl: "https://sap.com/careers/devops-engineer",
    description: "SAP is hiring DevOps Engineers to manage cloud infrastructure. Work with AWS, Docker, and Kubernetes. Set up CI/CD pipelines for enterprise software. Join a global enterprise software company."
  },
  {
    id: 53,
    title: "Data Engineer",
    company: "Dell",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Spark", "Kafka", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "12–18 LPA",
    applyUrl: "https://dell.com/careers/data-engineer",
    description: "Dell is looking for Data Engineers to build data pipelines. Process large datasets for business intelligence. Work with Spark and Kafka. Join a leading technology company."
  },
  {
    id: 54,
    title: "Frontend Developer",
    company: "Microsoft",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "TypeScript", "CSS", "Azure"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "8–12 LPA",
    applyUrl: "https://microsoft.com/careers/frontend-dev",
    description: "Microsoft is hiring Frontend Developers to build cloud interfaces. Work with React and TypeScript. Create user interfaces for Azure platform. Learn from world-class engineers."
  },
  {
    id: 55,
    title: "Backend Developer",
    company: "ThoughtWorks",
    location: "Pune",
    mode: "Remote",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "Microservices", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "12–20 LPA",
    applyUrl: "https://thoughtworks.com/careers/backend-dev",
    description: "ThoughtWorks is looking for Backend Developers to work on client projects. Build scalable APIs using Spring Boot. Work in agile teams. Great culture and learning opportunities."
  },
  {
    id: 56,
    title: "Full Stack Developer",
    company: "Zoho",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Node.js", "PostgreSQL", "TypeScript"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://careers.zoho.com/fullstack-dev",
    description: "Zoho is hiring Full Stack Developers to build SaaS products. Work on both frontend and backend systems. Use React, Node.js, and TypeScript. Join a product-focused company."
  },
  {
    id: 57,
    title: "Mobile Developer",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React Native", "JavaScript", "Redux", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://freshworks.com/careers/mobile-dev",
    description: "Freshworks is looking for Mobile Developers to build SaaS mobile apps. Work with React Native to create cross-platform apps. Build features for business users. Join a product-focused company."
  },
  {
    id: 58,
    title: "QA Engineer",
    company: "Juspay",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["Selenium", "Java", "TestNG", "API Testing"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "8–14 LPA",
    applyUrl: "https://juspay.in/careers/qa-engineer",
    description: "Juspay is hiring QA Engineers to test payment SDKs. Write automated test cases using Selenium. Ensure quality of fintech products. Join a fintech company focused on payments."
  },
  {
    id: 59,
    title: "DevOps Engineer",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "10–16 LPA",
    applyUrl: "https://paytm.com/careers/devops-engineer",
    description: "Paytm is looking for DevOps Engineers to manage payment infrastructure. Work with AWS and Kubernetes. Set up CI/CD pipelines. Join India's leading payment platform."
  },
  {
    id: 60,
    title: "Data Scientist",
    company: "Myntra",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["Python", "Machine Learning", "SQL", "Pandas"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "12–20 LPA",
    applyUrl: "https://myntra.com/careers/data-scientist",
    description: "Myntra is hiring Data Scientists to work on recommendation systems. Build ML models for fashion e-commerce. Analyze customer behavior data. Join India's leading fashion e-commerce platform."
  }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = jobData;
}
